# Generated by Django 4.0.5 on 2022-07-02 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characteristics', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('age', models.IntegerField()),
                ('weight', models.FloatField()),
                ('characteristics', models.ManyToManyField(to='characteristics.characteristic')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='groups.group')),
            ],
        ),
    ]
